#!/usr/bin/perl
# -*- perl -*-
#
# VULCANIZE
#
# $Revision: 0.5 $
#
# Sloppy job of mostly converting LaTeX documents to HTML
#
# Coyright 1994 M-J. Dominus and the Trustees of the University of
# Pennsylvania.  All rights reserved. 
#
# M-J Dominus (mjd@saul.cis.upenn.edu)
#
# Please see man page and manifesto at 
# http://www.cis.upenn.edu/~mjd/vulcanize.html.


$revno='$Revision: 0.5 $';
$revno =~ s/^.*:\s*//;
$revno =~ s/\$\s*$//;

$/='\x00';          # Slurp in entire file
$_ = <>;

s/^(\%[^\n]*\n)+//g;        # Discard comments: what's on a line
s/([^\\])\%[^\n]*\n/\1/g;       # after a line-beginning or non\'d %.

# Insert paragrpah marks
s/\n\n+/\<P\>\n\n/g;        

# Handle lists
s/\\begin\{enumerate\}/\<OL\>/g;
s/\\end\{enumerate\}/\<\/OL\>/g;
s/\\begin\{itemize\}/\<UL\>/g;
s/\\end\{itemize\}/\<\/UL\>/g;
s/\\begin\{description\}/\<DL\>/g;
s/\\end\{description\}/\<\/DL\>/g;

# items without []'s for <li>s; otherwise as <dt>[]<dd>
s/\\item\s*\[([^\]]*)\]/\<dt\>\1\<dd\>/g;
s/\\item/\<LI\>/g;

# Handle quotes
s/\\begin\{quotation\}/\<blockquote\>/g;
s/\\end\{quotation\}/\<\/blockquote\>/g;
s/\\begin\{quote\}/\<blockquote\>/g;
s/\\end\{quote\}/\<\/blockquote\>/g;

# Handle preformatted text
s/\\begin\{verbatim\}/\<pre\>/g;
s/\\end\{verbatim\}/\<\/pre\>/g;
s/\\begin\{tabbing\}/\<pre\>/g;
s/\\end\{tabbing\}/\<\/pre\>/g;
s/\\begin\{verse\}/\<pre\>/g;
s/\\end\{verse\}/\<\/pre\>/g;

# Handle entities
s/\\\&/&amp\;/g;
s/\\\</\&lt\;/g;
s/\\\>/\&gt\;/g;

# Real percent signs.
s/\\\%/\%/g;
s/\\\#/\#/g;

# Tex's hard space
s/\\ / /g;

# Accents---add more here as used.
s/\\\'([AEIOUYaeiouy])\s+/\&\1acute\;/g;
s/\\\"([AEIOUaeiouy])\s+/\&\1uml\;/g;
s/\\\`([AEIOUaeiou])\s+/\&\1grave\;/g;
s/\\\~([ANOano])\s+/\&\1tilde\;/g;
s/\\\^([AEIOUaeiou])\s+/\&\1circ\;/g;
s/\\\,([Cc])\s+/\&\1cedil\;/g;
s/\\([aoAO][Ee])\s+/\&\1lig\;/g;
s/\\ss/\&szlig\;/g;
s/\\aa/\&aring\;/g;
s/\\AA/\&Aring\;/g;
s/\\([Oo])\s+/\&\1slash\;/g;


# Miscellany that we can actually handle
s/\\ldots/.../g;
s/\\leq/\&lt;=/g;
s/\\geq/\&gt;=/g;

# We SHOULD translate these to &nbsp;
# (see http://info.cern.ch/hypertext/WWW/MarkUp/Entities.html)
# but guess what?
# Mosaic doesn't understand &nbsp, so we won't.  Duhhh.
s/([^\\])\~/\1 /g;      # Remove twiddle only when preceded by other 
s/^\~/ /g;          # than \ or when alone at beginning of line

s/\\\\\s*$/<br>/g;      # \\ at end of line -> <br>
s/\"/\&quot;/g;         # " -> &quot;

# handle formatting requests
s/\\verb\+([^+]*)\+/\<tt\>\1\<\/tt\>/g; # Doesn't work unless \verb+...+
s/\s*\{\\em\s*([^}]*)\}/ <em>\1<\/em>/g;
s/\s*\{\\bf\s*([^}]*)\}/ <b>\1<\/b>/g;
s/\s*\{\\sc\s*([^}]*)\}/ \U\1\E/g;
s/\s*\{\\it\s*([^}]*)\}/ <i>\1<\/i>/g;
s/\s*\{\\tt\s*([^}]*)\}/ <tt>\1<\/tt>/g;
s/\\begin\{em\}/\<em\>/g;
s/\\end\{em\}/\<\/em\>/g;
s/\\begin\{bf\}/\<b\>/g;
s/\\end\{bf\}/\<\/b\>/g;
s/\\begin\{it\}/\<i\>/g;
s/\\end\{it\}/\<\/i\>/g;
s/\\begin\{tt\}/\<tt\>/g;
s/\\end\{tt\}/\<\tt\>/g;

# Discard italic correction `\/'
s/\\\///g;

# Discard \noindent (it's hopeless)
s/\\noindent//g;

# Section headers
s/\\section\s*\{([^}]*)\}/<h1>$1<\/h1>/g;
s/\\subsection\s*\{([^}]*)\}/<h2>$1<\/h2>/g;
s/\\subsubsection\s*\{([^}]*)\}/<h3>$1<\/h3>/g;

# Remove <P> when it follows some other tag and is thereofre unnecessary
# e.g., </h2><P> --> </h2>
# This doesn't work well---fix it.
s/\>\s*\<[Pp]\>/\>/g;

s/\\index\{([^}]*)\}/\<a name\=\"ind-$1\"\>/g;
# Labels and refs

$count = 1;

while (/\\label\W\s*\{/) {
    s/\\label\W\s*\{([^}]*)\}/<a name\=\"ref-$1\"\>/;
    $labels{$1} = $count;
    $count += 1;
}
s/\\ref\{([^}]*)\}/<a href\=\"#ref-$1\"\>$labels{$1}\<\/a\>/g;

# Things we'll never add:
# centering, subscripts, superscripts, other math formulas. 
# fonts, parshape
# everything else.

$address=$ENV{'USER'} . '@' . `hostname`;
chop $address;

$header = "<title>TITLE GOES HERE</title>\n" . 
    "<!--  Generated by Vulcanize v$revno. >\n<!-- Whom to blame: M-J. Dominus, mjd@saul.cis.upenn.edu>\n" .
    "<H1>NEW PAGE</H1><p>\n" ;

$trailer =     "<P><HR>\<p\>\n\<ADDRESS\>\n$address\n\<\/ADDRESS\>\n";
# $trailer = "\<inc srv \"\/\~mjd\/lec\-notes\/lecnotes\-trailer\.html\"\>\b";

$footnotenumber=1;
$footnotes='';
while (/\\footnote/) {
    s/\\footnote\{([^}]*)\}/ \<a href\=\"#footnote-$footnotenumber\"\>\($footnotenumber\) \<\/a\>/;
    $footnotes .= "\<a name\=\"footnote-$footnotenumber\"\>\<li\> $1\<\/a\>\n";
$footnotenumber++;
}

if ($footnotes) {
    $footnotes = "\<hr\>\n\<h1\>Footnotes\<\/h1\>\<ol\>\n" . $footnotes . "\n\<\/ol\>\n";
}

# get rid of redundant curly braces;
# make curly braces we want, normal
# s/([^\\])[{}]/$1/g;
# s/\\([{}])/$1/g;

# Prepend title and header, append address.
$_ = $header .     $_ . $footnotes . $trailer;



# Urp.
print $_;

__END__


